### ISSUE TITLE
使用AS 3.0编译报错

### ISSUE THREAD

**Issue by Yasin27878** [shoyu666/derocoodemo#7]
使用AS 3.0出错  提示找不到processManifest,我了解到是新版本的AS对应的编译版本的语法更新了
Error:Could not get unknown property 'processManifest' for VariantOutput container of type org.gradle.api.internal.FactoryNamedDomainObjectContainer.

目前只能使用老版本 比如classpath 'com.android.tools.build:gradle:2.4.0-alpha7'

**Comment by shoyu666** [comment]
@Yasin27878  你好，这个项目可以用来学习研究，如果需要生产使用，建议https://github.com/Tencent/tinker
